# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8386f6e19db19d20530c2b700e260a5bf00060ffc3b453ee8c52334109b8ea02b663c0936a7e7939c29385e8235008860f5d545aa0dfb3f53a90f41e4cb338

test:
  secret_key_base: e66c886201d59a3051af06fbb93cd71328d581cfec6beff91fc92529946dcfe39fb91a1ddfe657f44cdcfe71b862233834956f51d9d92b7b336a6fc58af198ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
